# config/run_params.yaml

# General settings
script_dir: "/home/23r8105_messou/lab/time_series_augmentation_mix"
gpus: 2
model: "cnn"
optimizer: "adam"
interpret_method: "lime"

# Datasets to process
gnome_data:
  - ELECTRICITY_GLOBAL_REACTIVE_POWER
  - ELECTRICITY_MOUSE_HEALTH_ESTELA
  - ELECTRICITY_MOUSE_SCIENCE_MICHEAL
  - GAS_PANTHER_EDUCATION_MOHAMMAD
  - GAS_PANTHER_LODGING_DEAN
  - HOTWATER_FOX_LODGING_ALANA
  - HOTWATER_ROBIN_EDUCATION_MARGARITO
  - SOLAR_BOBCAT_EDUCATION_ALISSA
  - SOLAR_BOBCAT_EDUCATION_COLEMAN
  - WATER_PANTHER_LODGING_CORA
  - WATER_WOLF_EDUCATION_URSULA
  #- ELECTRICITY_GLOBAL_REACTIVE_POWER

# Augmentation techniques to apply
augmentation_methods:
  - sequential_combined4
  - sequential_combined5
  - sequential_combined7
  - sequential_combined12
  - parallel_combined3
  - parallel_combined4
  - parallel_combined10
  - parallel_combined12
